---
#
# Ansible managed
#
repository:
  description: phpMyAdmin installation for Linux
  homepage: https://buluma.github.io/
  topics: database, development, web, mysql, mariadb, php, phpmyadmin, ansible, molecule, tox, playbook, hacktoberfest
