---
- name: Converge
  hosts: all
  become: true

  vars:
    php_version: "7.3"
    phpmyadmin_enablerepo: "remi,remi-php73"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.repo-remi  # TODO: Rebuild
      when: ansible_os_family == 'RedHat'
    - role: buluma.apache
    - role: buluma.mysql
    - role: buluma.php_versions
    - role: buluma.php
    - role: geerlingguy.php-mysql  # TODO: Rebuild
    - role: buluma.phpmyadmin

  post_tasks:
    - name: Ensure phpMyAdmin is running.
      ansible.builtin.uri:
        url: "http://127.0.0.1/phpmyadmin/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
