---
- name: Converge
  hosts: all
  become: true

  vars:
    php_version: "7.3"
    phpmyadmin_enablerepo: "remi,remi-php73"
    phpmyadmin_mysql_user: sp3cial_us3r
    phpmyadmin_mysql_password: s3cure_password_h3r3

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    # - role: geerlingguy.repo-remi  # TODO: Rebuild
    #   when: ansible_os_family == 'RedHat'
    # - role: geerlingguy.apache
    # - role: geerlingguy.mysql
    # - role: buluma.php_versions
    # - role: geerlingguy.php
    # - role: geerlingguy.php-mysql  # TODO: Rebuild
    - role: buluma.phpmyadmin

  post_tasks:
    - name: Ensure phpMyAdmin is running.
      ansible.builtin.uri:
        url: "http://127.0.0.1/phpmyadmin/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
